---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by miraclerhe.
--- DateTime: 2022/12/27 17:22
---


---@class ChatRedpacketManager:ModuleBase
local ChatRedpacketManager = {}

function ChatRedpacketManager:OnInitialize()
	self.cachedRecord = {}
end

function ChatRedpacketManager:MarkStatus(guid,status)
	self.cachedRecord[guid] = status
end

--todo [miraclerhe] impl!
local a = 0
function ChatRedpacketManager:GetStatus(guid)
	a =a+1
	return a%3
	--return self.cachedRecord[guid]
end

--- 切游戏状态时（可用于清理数据）
function ChatRedpacketManager:OnPreSwitchGameStatus(pre, next)
end

local class = require("class")
local CModuleBase = require("client.module_framework.ModuleBase")
local CChatRedpacketManager = class(CModuleBase, nil, ChatRedpacketManager)

return CChatRedpacketManager
